// Command gendocs extracts each registered module's Go doc comment
// (already written on its module<Name> function — this project's
// convention has always been to document arguments and every
// deviation from real Ansible's behavior there) and emits
// docs_generated.go: a map from the module's registered name to that
// comment text, for ansible-doc to print without needing the source
// tree at runtime.
//
// Run via `go generate ./...` from the modules package (see the
// //go:generate directive in registry.go).
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run() error {
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	// go:generate runs with cwd set to the directory containing the
	// //go:generate directive — modules/ itself.
	fset := token.NewFileSet()
	notTest := func(info os.FileInfo) bool { return !strings.HasSuffix(info.Name(), "_test.go") }
	pkgs, err := parser.ParseDir(fset, dir, notTest, parser.ParseComments)
	if err != nil {
		return err
	}
	pkg, ok := pkgs["modules"]
	if !ok {
		return fmt.Errorf("no \"modules\" package found in %s", dir)
	}

	// funcDocs: Go identifier (e.g. "moduleSetup") -> its doc comment.
	funcDocs := map[string]string{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Doc == nil {
				continue
			}
			funcDocs[fn.Name.Name] = cleanDoc(fn.Doc.Text())
		}
	}

	// registrations: registered name -> Go identifier, read from every
	// r.Register("name", identifier) call anywhere in the package
	// (registry.go holds them all today, but scanning the whole
	// package means a future split file still works).
	type registration struct{ name, ident string }
	var regs []registration
	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || sel.Sel.Name != "Register" || len(call.Args) != 2 {
				return true
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}
			name, err := strconv.Unquote(lit.Value)
			if err != nil {
				return true
			}
			ident, ok := call.Args[1].(*ast.Ident)
			if !ok {
				return true
			}
			regs = append(regs, registration{name: name, ident: ident.Name})
			return true
		})
	}
	if len(regs) == 0 {
		return fmt.Errorf("found no r.Register(\"name\", moduleFn) calls in %s", dir)
	}

	sort.Slice(regs, func(i, j int) bool { return regs[i].name < regs[j].name })

	var b strings.Builder
	b.WriteString("// Code generated by modules/internal/gendocs. DO NOT EDIT.\n")
	b.WriteString("// Run `go generate ./...` from the modules package to regenerate\n")
	b.WriteString("// after adding, removing, or re-documenting a module.\n\n")
	b.WriteString("package modules\n\n")
	b.WriteString("// Docs maps every registered module name to its Go doc comment —\n")
	b.WriteString("// the same argument/deviation documentation this project has always\n")
	b.WriteString("// written on each module<Name> function, extracted once at build\n")
	b.WriteString("// time so ansible-doc can print it without the source tree present.\n")
	b.WriteString("var Docs = map[string]string{\n")
	for _, r := range regs {
		doc, ok := funcDocs[r.ident]
		if !ok {
			doc = "(no documentation comment on " + r.ident + ")\n"
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", r.name, doc)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("formatting generated source: %w", err)
	}
	out := filepath.Join(dir, "docs_generated.go")
	return os.WriteFile(out, formatted, 0o644)
}

// cleanDoc trims the doc comment's own leading "// module<Name>
// implements Ansible's `x` module: ..." boilerplate down to just the
// comment body go/doc already gives us (ast.CommentGroup.Text already
// strips comment markers and normalizes leading whitespace) — nothing
// further needed, kept as a named step in case future formatting
// wants a hook here.
func cleanDoc(text string) string {
	return strings.TrimRight(text, "\n") + "\n"
}
