package modules

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"testing"

	remoteexec "github.com/go-remoteexec/transport"
)

// hybridConn fakes Exec for whatever commands are listed in `on` and
// falls back to a REAL local.Exec for everything else (in particular
// `test -e ...`, used by fetchIfExists/pathExists), while Put/Fetch/
// Remove/TempPath/Close all go to the real remoteexec.Local — needed
// for iptables_state.go's tests, which round-trip real file content
// through writeRemote/fetchIfExists and so need those to actually work
// against the temp files these tests create, unlike fakeConn's Put/
// Fetch, which are no-ops.
type hybridConn struct {
	local *remoteexec.Local
	on    map[string]remoteexec.Result
}

func newHybridConn(on map[string]remoteexec.Result) *hybridConn {
	return &hybridConn{local: local(), on: on}
}

func (h *hybridConn) Exec(ctx context.Context, cmd string, stdin io.Reader) (remoteexec.Result, error) {
	if res, ok := h.on[cmd]; ok {
		return res, nil
	}
	return h.local.Exec(ctx, cmd, stdin)
}
func (h *hybridConn) Put(ctx context.Context, localPath, remotePath string, opts remoteexec.PutOptions) error {
	return h.local.Put(ctx, localPath, remotePath, opts)
}
func (h *hybridConn) Fetch(ctx context.Context, remotePath, localPath string) error {
	return h.local.Fetch(ctx, remotePath, localPath)
}
func (h *hybridConn) Remove(ctx context.Context, remotePath string) error {
	return h.local.Remove(ctx, remotePath)
}
func (h *hybridConn) TempPath(base string) string { return h.local.TempPath(base) }
func (h *hybridConn) Close() error                { return h.local.Close() }

var _ remoteexec.Connection = (*hybridConn)(nil)

const iptablesSaveOut = "# Generated by iptables-save v1.8.7 on Mon Jan  1 00:00:00 2024\n" +
	"*filter\n" +
	":INPUT ACCEPT [10:1000]\n" +
	":FORWARD ACCEPT [0:0]\n" +
	":OUTPUT ACCEPT [5:500]\n" +
	"-A INPUT -i lo -j ACCEPT\n" +
	"COMMIT\n" +
	"# Completed on Mon Jan  1 00:00:00 2024\n"

func TestModuleIptablesStateSavedNewFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "iptables.rules")
	conn := newHybridConn(map[string]remoteexec.Result{
		"command -v iptables-save >/dev/null 2>&1 && command -v iptables-restore >/dev/null 2>&1": {RC: 0},
		"iptables-save": {RC: 0, Stdout: iptablesSaveOut},
	})
	res, err := moduleIptablesState(context.Background(), conn, map[string]any{"state": "saved", "path": path})
	if err != nil {
		t.Fatal(err)
	}
	if !res.Changed {
		t.Fatalf("res = %+v", res)
	}
	tables := res.Extra["tables"].(map[string][]string)
	if _, ok := tables["filter"]; !ok {
		t.Fatalf("tables = %#v", tables)
	}
}

func TestModuleIptablesStateSavedIdempotent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "iptables.rules")
	// pre-write the EXACT content the module would produce (counters
	// zeroed, timestamps stripped down to the bare comment, but not
	// removed entirely) so the second run is a no-op.
	expected := "# Generated by iptables-save v1.8.7\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n" +
		":OUTPUT ACCEPT [0:0]\n-A INPUT -i lo -j ACCEPT\nCOMMIT\n# Completed\n"
	if err := os.WriteFile(path, []byte(expected), 0o644); err != nil {
		t.Fatal(err)
	}
	conn := newHybridConn(map[string]remoteexec.Result{
		"command -v iptables-save >/dev/null 2>&1 && command -v iptables-restore >/dev/null 2>&1": {RC: 0},
		"iptables-save": {RC: 0, Stdout: iptablesSaveOut},
	})
	res, err := moduleIptablesState(context.Background(), conn, map[string]any{"state": "saved", "path": path})
	if err != nil {
		t.Fatal(err)
	}
	if res.Changed {
		t.Fatalf("res = %+v, want unchanged: counters/timestamp differences must not count", res)
	}
}

func TestModuleIptablesStateRestoreMissingSource(t *testing.T) {
	conn := newHybridConn(map[string]remoteexec.Result{
		"command -v iptables-save >/dev/null 2>&1 && command -v iptables-restore >/dev/null 2>&1": {RC: 0},
	})
	res, err := moduleIptablesState(context.Background(), conn, map[string]any{
		"state": "restored", "path": filepath.Join(t.TempDir(), "does-not-exist"),
	})
	if err != nil {
		t.Fatal(err)
	}
	if !res.Failed {
		t.Fatal("want failed for missing source file")
	}
}

func TestModuleIptablesStateRestoreSuccess(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "iptables.rules")
	if err := os.WriteFile(path, []byte(iptablesSaveOut), 0o644); err != nil {
		t.Fatal(err)
	}
	conn := newHybridConn(map[string]remoteexec.Result{
		"command -v iptables-save >/dev/null 2>&1 && command -v iptables-restore >/dev/null 2>&1": {RC: 0},
		"iptables-save": {RC: 0, Stdout: "*filter\n:INPUT DROP [0:0]\nCOMMIT\n"},
		"iptables-restore --test " + shellQuote(path): {RC: 0},
		"iptables-restore " + shellQuote(path):        {RC: 0},
	})
	res, err := moduleIptablesState(context.Background(), conn, map[string]any{"state": "restored", "path": path})
	if err != nil {
		t.Fatal(err)
	}
	if res.Failed {
		t.Fatalf("res = %+v", res)
	}
	if res.Extra["applied"] != true {
		t.Fatalf("applied = %v", res.Extra["applied"])
	}
}

func TestModuleIptablesStateRestoreTestFails(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "iptables.rules")
	if err := os.WriteFile(path, []byte(iptablesSaveOut), 0o644); err != nil {
		t.Fatal(err)
	}
	conn := newHybridConn(map[string]remoteexec.Result{
		"command -v iptables-save >/dev/null 2>&1 && command -v iptables-restore >/dev/null 2>&1": {RC: 0},
		"iptables-save": {RC: 0, Stdout: iptablesSaveOut},
		"iptables-restore --test " + shellQuote(path): {RC: 1, Stderr: "malformed rule\n"},
	})
	res, err := moduleIptablesState(context.Background(), conn, map[string]any{"state": "restored", "path": path})
	if err != nil {
		t.Fatal(err)
	}
	if !res.Failed {
		t.Fatal("want failed when --test fails")
	}
	if res.Extra["applied"] != false {
		t.Fatalf("applied = %v", res.Extra["applied"])
	}
}

func TestModuleIptablesStateTableNotInFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "iptables.rules")
	if err := os.WriteFile(path, []byte(iptablesSaveOut), 0o644); err != nil {
		t.Fatal(err)
	}
	conn := newHybridConn(map[string]remoteexec.Result{
		"command -v iptables-save >/dev/null 2>&1 && command -v iptables-restore >/dev/null 2>&1": {RC: 0},
	})
	res, err := moduleIptablesState(context.Background(), conn, map[string]any{
		"state": "restored", "path": path, "table": "nat",
	})
	if err != nil {
		t.Fatal(err)
	}
	if !res.Failed {
		t.Fatal("want failed when table not present in restore file")
	}
}

func TestModuleIptablesStateInvalidState(t *testing.T) {
	conn := newFakeConn(nil)
	if _, err := moduleIptablesState(context.Background(), conn, map[string]any{"state": "bogus", "path": "/x"}); err == nil {
		t.Fatal("want error")
	}
}

func TestIptablesFilterFormatStripsTimestampsAndCounters(t *testing.T) {
	lines := iptablesFilterFormat(iptablesSaveOut, false)
	for _, l := range lines {
		if l == "# Generated by iptables-save v1.8.7 on Mon Jan  1 00:00:00 2024" {
			t.Fatal("timestamp should be stripped")
		}
	}
	found := false
	for _, l := range lines {
		if l == ":INPUT ACCEPT [0:0]" {
			found = true
		}
	}
	if !found {
		t.Fatalf("counters should be zeroed: %v", lines)
	}
}

func TestIptablesFilterFormatKeepsCounters(t *testing.T) {
	lines := iptablesFilterFormat(iptablesSaveOut, true)
	found := false
	for _, l := range lines {
		if l == ":INPUT ACCEPT [10:1000]" {
			found = true
		}
	}
	if !found {
		t.Fatalf("counters should be preserved when counters=true: %v", lines)
	}
}

func TestIptablesParsePerTable(t *testing.T) {
	tables := iptablesParsePerTable(iptablesSaveOut, false)
	filter, ok := tables["filter"]
	if !ok {
		t.Fatalf("tables = %#v", tables)
	}
	found := false
	for _, l := range filter {
		if l == "-A INPUT -i lo -j ACCEPT" {
			found = true
		}
	}
	if !found {
		t.Fatalf("filter = %v", filter)
	}
}
