package modules

// registerBuiltins registers this package's built-in module set onto r.
func registerBuiltins(r *Registry) {
	r.Register("command", moduleCommand)
	r.Register("shell", moduleShell)
	r.Register("copy", moduleCopy)
	r.Register("file", moduleFile)
	r.Register("template", moduleTemplate)
	r.Register("lineinfile", moduleLineinfile)
	r.Register("replace", moduleReplace)
	r.Register("stat", moduleStat)
	r.Register("debug", moduleDebug)
	r.Register("assert", moduleAssert)
	r.Register("fail", moduleFail)
	r.Register("set_fact", moduleSetFact)
	r.Register("cron", moduleCron)
	r.Register("user", moduleUser)
	r.Register("group", moduleGroup)
	r.Register("systemd", moduleSystemd)
	r.Register("service", moduleSystemd) // "service" is systemd's classic alias on modern distros
	r.Register("apt", moduleApt)
	r.Register("pip", modulePip)
	r.Register("git", moduleGit)
	r.Register("ping", modulePing)
	r.Register("slurp", moduleSlurp)
	r.Register("tempfile", moduleTempfile)
	r.Register("fetch", moduleFetch)
	r.Register("find", moduleFind)
	r.Register("get_url", moduleGetURL)
	r.Register("uri", moduleURI)
	r.Register("wait_for", moduleWaitFor)
	r.Register("hostname", moduleHostname)
	r.Register("getent", moduleGetent)
	r.Register("apt_key", moduleAptKey)
	r.Register("apt_repository", moduleAptRepository)
	r.Register("blockinfile", moduleBlockinfile)
	r.Register("debconf", moduleDebconf)
	r.Register("dnf", moduleDnf)
	r.Register("dnf5", moduleDnf5)
	r.Register("dpkg_selections", moduleDpkgSelections)
	r.Register("package", modulePackage)
	r.Register("package_facts", modulePackageFacts)
	r.Register("service_facts", moduleServiceFacts)
}
